import { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

const translations = {
  en: {
    dashboard: 'Dashboard',
    shop: 'Store',
    profile: 'Profile',
    settings: 'Settings',
    logout: 'Logout',
    login: 'Login',
    signup: 'Sign Up',
    leaderboard: 'Leaderboard',
    friends: 'Friends',
    notifications: 'Notifications',
    premium: 'Premium',
    gameModes: 'Game Modes',
    singlePlayer: 'Single Player',
    duos: 'Duos',
    team: 'Team',
    ranked: 'Ranked',
    exams: 'Exams',
    progress: 'Progress',
    startLearning: 'Start Learning',
    backTo: 'Back to',
    lessons: 'Lessons',
    achievements: 'Achievements',
    streak: 'Streak',
    level: 'Level',
    xp: 'XP',
    hours: 'Hours',
    score: 'Score',
    // Additional translations
    welcomeBack: 'Welcome back!',
    learningProgress: 'Here\'s your learning progress and AI-powered recommendations.',
    currentGrades: 'Current Grades',
    sync: 'Sync',
    aiRecommendations: 'AI Recommendations',
    personalizedRecommendations: 'Personalized recommendations based on your performance',
    quickActions: 'Quick Actions',
    getStarted: 'Get Started',
    viewProgress: 'View Progress',
    days: 'days',
    day: 'day',
    streakCounter: '{{count}} days',
    streakCounter_one: '{{count}} day',
    streakCounter_other: '{{count}} days',
    hoursLearned: '{{count}} hours',
    hoursLearned_one: '{{count}} hour',
    hoursLearned_other: '{{count}} hours',
    levelUp: 'Level {{level}}',
    xpProgress: '{{current}}/{{total}} XP',
    achievementsUnlocked: '{{count}} achievements',
    achievementsUnlocked_one: '{{count}} achievement',
    achievementsUnlocked_other: '{{count}} achievements',
    lessonsCompleted: '{{count}} lessons',
    lessonsCompleted_one: '{{count}} lesson',
    lessonsCompleted_other: '{{count}} lessons',
    // Progress page translations
    trackJourney: 'Track your learning journey and achievements',
    completed: 'Completed',
    avgScore: 'Avg Score',
    studyTime: 'Study Time',
    acrossQuizzes: 'across all quizzes',
    totalLearningTime: 'total learning time',
    trends: 'Trends',
    recentActivity: 'Recent Activity',
    recentlyAccessed: 'Your most recently accessed lessons',
    weeklyProgress: 'Weekly Progress',
    subjectPerformance: 'Subject Performance',
    outOf: 'out of',
    // Profile page translations
    addPeople: 'Add People',
    // Game modes translations
    challengeYourself: 'Challenge yourself and others in various learning formats',
    currentRank: 'Current Rank',
    next: 'Next',
    maxRank: 'Max Rank!',
    season: 'Season',
    progressTo: 'Progress to',
    max: 'Max',
    yourStats: 'Your Statistics',
    learningModules: 'Learning Modules',
    players: 'Players',
    difficulty: 'Difficulty',
    rewards: 'Rewards',
    start: 'Start',
    specializedLearning: 'Specialized Learning',
    explore: 'Explore',
    // Wellness tab translations
    wellness: 'Wellness',
    wellnessCheckins: 'Wellness Check-ins',
    mood: 'Mood',
    stress: 'Stress',
    notes: 'Notes',
    aiInsights: 'AI Insights',
    noCheckinsYet: 'No wellness check-ins yet',
    lastCheckin: 'Last check-in',
    daysAgo: '{{count}} days ago',
    daysAgo_one: '{{count}} day ago',
    daysAgo_other: '{{count}} days ago',
    // GameModes page translations
    programLearning: 'Program Learning',
    programLearningDesc: 'Personalized learning pathway based on your goals, proficiency level, and preferences.',
    schoolLearning: 'School Learning',
    schoolLearningDesc: 'Align learning with school curriculum and subjects',
    selfLearning: 'Self-Learning',
    selfLearningDesc: 'Personalized learning paths based on your interests',
    otherModules: 'Other Modules',
    otherModulesDesc: 'Specialized learning for specific use cases',
    jobInterviewPrep: 'Job Interview Prep',
    jobInterviewPrepDesc: 'Prepare for job interviews with AI simulations',
    presentationPrep: 'Presentation Prep',
    presentationPrepDesc: 'Improve your presentation skills with AI feedback',
    hobbyLearning: 'Hobby Learning',
    hobbyLearningDesc: 'Learn new skills and hobbies in a structured way',
    learningPathways: 'Learning Pathways',
    learningPathwaysDesc: 'Choose a learning pathway that suits your goals and preferences',
    recommended: 'Recommended',
    startPersonalizedPlan: 'Start Personalized Plan',
    selectPathway: 'Select Pathway'
  },
  lt: {
    dashboard: 'Valdymo skydas',
    shop: 'Parduotuvė',
    profile: 'Profilis',
    settings: 'Nustatymai',
    logout: 'Atsijungti',
    login: 'Prisijungti',
    signup: 'Registruotis',
    leaderboard: 'Lyderių lenta',
    friends: 'Draugai',
    notifications: 'Pranešimai',
    premium: 'Premium',
    gameModes: 'Žaidimo režimai',
    singlePlayer: 'Vienas žaidėjas',
    duos: 'Duetai',
    team: 'Komanda',
    ranked: 'Reitinguotas',
    exams: 'Egzaminai',
    progress: 'Pažanga',
    startLearning: 'Pradėti mokytis',
    backTo: 'Grįžti į',
    lessons: 'Pamokos',
    achievements: 'Pasiekimai',
    streak: 'Serija',
    level: 'Lygis',
    xp: 'Patirtis',
    hours: 'Valandos',
    score: 'Rezultatas',
    // Additional translations
    welcomeBack: 'Sveiki sugrįžę!',
    learningProgress: 'Čia pateikta jūsų mokymosi pažanga ir rekomendacijos pagal AI.',
    currentGrades: 'Dabartiniai pažymiai',
    sync: 'Sinchronizuoti',
    aiRecommendations: 'AI rekomendacijos',
    personalizedRecommendations: 'Suasmenintos rekomendacijos pagal jūsų pasiekimus',
    quickActions: 'Greiti veiksmai',
    getStarted: 'Pradėti',
    viewProgress: 'Peržiūrėti pažangą',
    days: 'dienos',
    day: 'diena',
    streakCounter: '{{count}} dienų',
    streakCounter_one: '{{count}} diena',
    streakCounter_other: '{{count}} dienos',
    hoursLearned: '{{count}} valandų',
    hoursLearned_one: '{{count}} valanda',
    hoursLearned_other: '{{count}} valandos',
    levelUp: '{{level}} lygis',
    xpProgress: '{{current}}/{{total}} XP',
    achievementsUnlocked: '{{count}} pasiekimų',
    achievementsUnlocked_one: '{{count}} pasiekimas',
    achievementsUnlocked_other: '{{count}} pasiekimai',
    lessonsCompleted: '{{count}} pamokų',
    lessonsCompleted_one: '{{count}} pamoka',
    lessonsCompleted_other: '{{count}} pamokos',
    // Progress page translations
    trackJourney: 'Stebėkite savo mokymosi procesą ir pasiekimus',
    completed: 'Užbaigta',
    avgScore: 'Vid. balas',
    studyTime: 'Mokymosi laikas',
    acrossQuizzes: 'visuose testuose',
    totalLearningTime: 'bendras mokymosi laikas',
    trends: 'Tendencijos',
    recentActivity: 'Naujausia veikla',
    recentlyAccessed: 'Jūsų neseniai atidarytos pamokos',
    weeklyProgress: 'Savaitės progresas',
    subjectPerformance: 'Dalykų rezultatai',
    outOf: 'iš',
    // Profile page translations
    addPeople: 'Pridėti žmonių',
    // Game modes translations
    challengeYourself: 'Iššaukite save ir kitus įvairiais mokymosi formatais',
    currentRank: 'Dabartinis rangas',
    next: 'Kitas',
    maxRank: 'Maksimalus rangas!',
    season: 'Sezonas',
    progressTo: 'Progresas iki',
    max: 'Maks.',
    yourStats: 'Jūsų statistika',
    learningModules: 'Mokymosi moduliai',
    players: 'Žaidėjai',
    difficulty: 'Sudėtingumas',
    rewards: 'Apdovanojimai',
    start: 'Pradėti',
    specializedLearning: 'Specializuotas mokymasis',
    explore: 'Tyrinėti',
    // Wellness tab translations
    wellness: 'Gerovė',
    wellnessCheckins: 'Gerovės registracijos',
    mood: 'Nuotaika',
    stress: 'Stresas',
    notes: 'Pastabos',
    aiInsights: 'DI įžvalgos',
    noCheckinsYet: 'Dar nėra gerovės registracijų',
    lastCheckin: 'Paskutinė registracija',
    daysAgo: 'prieš {{count}} dienų',
    daysAgo_one: 'prieš {{count}} dieną',
    daysAgo_other: 'prieš {{count}} dienas',
    // GameModes page translations
    programLearning: 'Programinis mokymasis',
    programLearningDesc: 'Individualizuotas mokymosi kelias pagal jūsų tikslus ir gebėjimus.',
    schoolLearning: 'Mokyklinis mokymasis',
    schoolLearningDesc: 'Mokymasis pagal mokyklos mokymo programą',
    selfLearning: 'Savarankiškas mokymasis',
    selfLearningDesc: 'Individualizuoti mokymosi keliai pagal jūsų pomėgius',
    otherModules: 'Kiti moduliai',
    otherModulesDesc: 'Specializuotas mokymasis konkretiems atvejams',
    jobInterviewPrep: 'Darbo pokalbio paruošimas',
    jobInterviewPrepDesc: 'Pasiruoškite darbo pokalbiams su DI simuliacijomis',
    presentationPrep: 'Prezentacijos paruošimas',
    presentationPrepDesc: 'Tobulinkite prezentavimo įgūdžius su DI atsiliepimais',
    hobbyLearning: 'Hobio mokymasis',
    hobbyLearningDesc: 'Išmokite naujų įgūdžių struktūrizuotai',
    learningPathways: 'Mokymosi keliai',
    learningPathwaysDesc: 'Pasirinkite mokymosi kelią, atitinkantį jūsų tikslus',
    recommended: 'Rekomenduojama',
    startPersonalizedPlan: 'Pradėti asmeninį planą',
    selectPathway: 'Pasirinkti kelią'
  },
  zh: {
    dashboard: '仪表板',
    shop: '商店',
    profile: '个人资料',
    settings: '设置',
    logout: '登出',
    login: '登录',
    signup: '注册',
    leaderboard: '排行榜',
    friends: '朋友',
    notifications: '通知',
    premium: '高级版',
    gameModes: '游戏模式',
    singlePlayer: '单人游戏',
    duos: '双人组队',
    team: '团队',
    ranked: '排位赛',
    exams: '考试',
    progress: '进度',
    startLearning: '开始学习',
    backTo: '返回',
    lessons: '课程',
    achievements: '成就',
    streak: '连续学习',
    level: '等级',
    xp: '经验值',
    hours: '小时',
    score: '分数',
    // Additional translations
    welcomeBack: '欢迎回来！',
    learningProgress: '这是您的学习进度和AI推荐。',
    currentGrades: '当前成绩',
    sync: '同步',
    aiRecommendations: 'AI推荐',
    personalizedRecommendations: '根据您的表现的个性化推荐',
    quickActions: '快速操作',
    getStarted: '开始',
    viewProgress: '查看进度',
    days: '天',
    day: '天',
    streakCounter: '{{count}} 天',
    streakCounter_one: '{{count}} 天',
    streakCounter_other: '{{count}} 天',
    hoursLearned: '{{count}} 小时',
    hoursLearned_one: '{{count}} 小时',
    hoursLearned_other: '{{count}} 小时',
    levelUp: '{{level}} 级',
    xpProgress: '{{current}}/{{total}} 经验值',
    achievementsUnlocked: '{{count}} 成就',
    achievementsUnlocked_one: '{{count}} 成就',
    achievementsUnlocked_other: '{{count}} 成就',
    lessonsCompleted: '{{count}} 课程',
    lessonsCompleted_one: '{{count}} 课程',
    lessonsCompleted_other: '{{count}} 课程',
    // Progress page translations
    trackJourney: '跟踪您的学习历程和成就',
    completed: '已完成',
    avgScore: '平均分',
    studyTime: '学习时间',
    acrossQuizzes: '所有测验',
    totalLearningTime: '总学习时间',
    trends: '趋势',
    recentActivity: '最近活动',
    recentlyAccessed: '您最近访问的课程',
    weeklyProgress: '每周进度',
    subjectPerformance: '科目表现',
    outOf: '共',
    // Profile page translations
    addPeople: '添加人员',
    // Game modes translations
    challengeYourself: '在各种学习形式中挑战自己和他人',
    currentRank: '当前排名',
    next: '下一个',
    maxRank: '最高排名！',
    season: '赛季',
    progressTo: '进步到',
    max: '最大',
    yourStats: '您的统计数据',
    learningModules: '学习模块',
    players: '玩家',
    difficulty: '难度',
    rewards: '奖励',
    start: '开始',
    specializedLearning: '专业学习',
    explore: '探索',
    // Wellness tab translations
    wellness: '健康',
    wellnessCheckins: '健康检查',
    mood: '情绪',
    stress: '压力',
    notes: '笔记',
    aiInsights: 'AI洞察',
    noCheckinsYet: '还没有健康检查',
    lastCheckin: '上次检查',
    daysAgo: '{{count}} 天前',
    daysAgo_one: '{{count}} 天前',
    daysAgo_other: '{{count}} 天前',
    // GameModes page translations
    programLearning: '程序学习',
    programLearningDesc: '根据您的目标和能力定制的个性化学习路径。',
    schoolLearning: '学校学习',
    schoolLearningDesc: '与学校课程和科目保持一致',
    selfLearning: '自主学习',
    selfLearningDesc: '根据您的兴趣定制的学习路径',
    otherModules: '其他模块',
    otherModulesDesc: '针对特定情况的专业学习',
    jobInterviewPrep: '面试准备',
    jobInterviewPrepDesc: '通过AI模拟准备工作面试',
    presentationPrep: '演示准备',
    presentationPrepDesc: '通过AI反馈提高演示技能',
    hobbyLearning: '爱好学习',
    hobbyLearningDesc: '以结构化的方式学习新技能',
    learningPathways: '学习路径',
    learningPathwaysDesc: '选择适合您目标的学习路径',
    recommended: '推荐',
    startPersonalizedPlan: '开始个性化计划',
    selectPathway: '选择路径'
  },
  ja: {
    dashboard: 'ダッシュボード',
    shop: 'ショップ',
    profile: 'プロフィール',
    settings: '設定',
    logout: 'ログアウト',
    login: 'ログイン',
    signup: 'サインアップ',
    leaderboard: 'リーダーボード',
    friends: '友達',
    notifications: '通知',
    premium: 'プレミアム',
    gameModes: 'ゲームモード',
    singlePlayer: 'シングルプレイヤー',
    duos: 'デュオ',
    team: 'チーム',
    ranked: 'ランキング',
    exams: '試験',
    progress: '進捗',
    startLearning: '学習を始める',
    backTo: '戻る',
    lessons: 'レッスン',
    achievements: '実績',
    streak: '連続記録',
    level: 'レベル',
    xp: '経験値',
    hours: '時間',
    score: 'スコア',
    // Additional translations
    welcomeBack: 'おかえりなさい！',
    learningProgress: 'こちらがあなたの学習状況とAIによる推奨です。',
    currentGrades: '現在の成績',
    sync: '同期',
    aiRecommendations: 'AI推奨',
    personalizedRecommendations: 'あなたのパフォーマンスに基づいたパーソナライズされた推奨事項',
    quickActions: 'クイックアクション',
    getStarted: '開始',
    viewProgress: '進捗を表示',
    days: '日',
    day: '日',
    streakCounter: '{{count}} 日',
    streakCounter_one: '{{count}} 日',
    streakCounter_other: '{{count}} 日',
    hoursLearned: '{{count}} 時間',
    hoursLearned_one: '{{count}} 時間',
    hoursLearned_other: '{{count}} 時間',
    levelUp: '{{level}} レベル',
    xpProgress: '{{current}}/{{total}} XP',
    achievementsUnlocked: '{{count}} 実績',
    achievementsUnlocked_one: '{{count}} 実績',
    achievementsUnlocked_other: '{{count}} 実績',
    lessonsCompleted: '{{count}} レッスン',
    lessonsCompleted_one: '{{count}} レッスン',
    lessonsCompleted_other: '{{count}} レッスン',
    // Progress page translations
    trackJourney: '学習の旅と実績を追跡する',
    completed: '完了',
    avgScore: '平均スコア',
    studyTime: '学習時間',
    acrossQuizzes: 'すべてのクイズで',
    totalLearningTime: '合計学習時間',
    trends: 'トレンド',
    recentActivity: '最近の活動',
    recentlyAccessed: '最近アクセスしたレッスン',
    weeklyProgress: '週次進捗',
    subjectPerformance: '科目別パフォーマンス',
    outOf: '/',
    // Profile page translations
    addPeople: '人々を追加',
    // Game modes translations
    challengeYourself: '様々な学習形式で自分自身や他の人と競争',
    currentRank: '現在のランク',
    next: '次',
    maxRank: '最高ランク！',
    season: 'シーズン',
    progressTo: '進行状況',
    max: '最大',
    yourStats: 'あなたの統計',
    learningModules: '学習モジュール',
    players: 'プレイヤー',
    difficulty: '難易度',
    rewards: '報酬',
    start: '開始',
    specializedLearning: '専門学習',
    explore: '探検',
    // Wellness tab translations
    wellness: 'ウェルネス',
    wellnessCheckins: 'ウェルネスチェックイン',
    mood: '気分',
    stress: 'ストレス',
    notes: 'ノート',
    aiInsights: 'AIインサイト',
    noCheckinsYet: 'まだウェルネスチェックインがありません',
    lastCheckin: '最終チェックイン',
    daysAgo: '{{count}}日前',
    daysAgo_one: '{{count}}日前',
    daysAgo_other: '{{count}}日前',
    // GameModes page translations
    programLearning: 'プログラム学習',
    programLearningDesc: '目標と能力に基づいたパーソナライズされた学習パス。',
    schoolLearning: '学校学習',
    schoolLearningDesc: '学校のカリキュラムに合わせた学習',
    selfLearning: '自己学習',
    selfLearningDesc: '興味に基づいたパーソナライズされた学習パス',
    otherModules: 'その他のモジュール',
    otherModulesDesc: '特定の目的のための専門学習',
    jobInterviewPrep: '面接準備',
    jobInterviewPrepDesc: 'AIシミュレーションで面接準備',
    presentationPrep: 'プレゼン準備',
    presentationPrepDesc: 'AIフィードバックでスキル向上',
    hobbyLearning: '趣味学習',
    hobbyLearningDesc: '構造化された方法で新しいスキルを学ぶ',
    learningPathways: '学習パスウェイ',
    learningPathwaysDesc: '目標に合った学習パスを選択',
    recommended: 'おすすめ',
    startPersonalizedPlan: 'パーソナライズプラン開始',
    selectPathway: 'パスを選択'
  },
  ko: {
    dashboard: '대시보드',
    shop: '상점',
    profile: '프로필',
    settings: '설정',
    logout: '로그아웃',
    login: '로그인',
    signup: '회원가입',
    leaderboard: '리더보드',
    friends: '친구',
    notifications: '알림',
    premium: '프리미엄',
    gameModes: '게임 모드',
    singlePlayer: '싱글 플레이어',
    duos: '듀오',
    team: '팀',
    ranked: '랭킹전',
    exams: '시험',
    progress: '진행 상황',
    startLearning: '학습 시작하기',
    backTo: '돌아가기',
    lessons: '레슨',
    achievements: '업적',
    streak: '연속 학습',
    level: '레벨',
    xp: '경험치',
    hours: '시간',
    score: '점수',
    // Additional translations
    welcomeBack: '다시 오신 것을 환영합니다!',
    learningProgress: '여기에 귀하의 학습 진행 상황과 AI 기반 추천이 있습니다.',
    currentGrades: '현재 성적',
    sync: '동기화',
    aiRecommendations: 'AI 추천',
    personalizedRecommendations: '성과에 따른 개인화된 추천',
    quickActions: '빠른 작업',
    getStarted: '시작하기',
    viewProgress: '진행 상황 보기',
    days: '일',
    day: '일',
    streakCounter: '{{count}} 일',
    streakCounter_one: '{{count}} 일',
    streakCounter_other: '{{count}} 일',
    hoursLearned: '{{count}} 시간',
    hoursLearned_one: '{{count}} 시간',
    hoursLearned_other: '{{count}} 시간',
    levelUp: '{{level}} 레벨',
    xpProgress: '{{current}}/{{total}} XP',
    achievementsUnlocked: '{{count}} 업적',
    achievementsUnlocked_one: '{{count}} 업적',
    achievementsUnlocked_other: '{{count}} 업적',
    lessonsCompleted: '{{count}} 레슨',
    lessonsCompleted_one: '{{count}} 레슨',
    lessonsCompleted_other: '{{count}} 레슨',
    // Progress page translations
    trackJourney: '학습 여정과 업적을 추적하세요',
    completed: '완료됨',
    avgScore: '평균 점수',
    studyTime: '학습 시간',
    acrossQuizzes: '모든 퀴즈에서',
    totalLearningTime: '총 학습 시간',
    trends: '트렌드',
    recentActivity: '최근 활동',
    recentlyAccessed: '최근 접근한 레슨',
    weeklyProgress: '주간 진행 상황',
    subjectPerformance: '과목별 성과',
    outOf: '/',
    // Profile page translations
    addPeople: '사람 추가',
    // Game modes translations
    challengeYourself: '다양한 학습 형식으로 자신과 다른 사람에게 도전',
    currentRank: '현재 순위',
    next: '다음',
    maxRank: '최고 순위!',
    season: '시즌',
    progressTo: '진행 상황',
    max: '최대',
    yourStats: '당신의 통계',
    learningModules: '학습 모듈',
    players: '플레이어',
    difficulty: '난이도',
    rewards: '보상',
    start: '시작',
    specializedLearning: '전문 학습',
    explore: '탐색',
    // Wellness tab translations
    wellness: '웰빙',
    wellnessCheckins: '웰빙 체크인',
    mood: '기분',
    stress: '스트레스',
    notes: '노트',
    aiInsights: 'AI 인사이트',
    noCheckinsYet: '아직 웰빙 체크인이 없습니다',
    lastCheckin: '마지막 체크인',
    daysAgo: '{{count}}일 전',
    daysAgo_one: '{{count}}일 전',
    daysAgo_other: '{{count}}일 전',
    // GameModes page translations
    programLearning: '프로그램 학습',
    programLearningDesc: '목표와 능력에 기반한 맞춤형 학습 경로.',
    schoolLearning: '학교 학습',
    schoolLearningDesc: '학교 커리큘럼에 맞춘 학습',
    selfLearning: '자기 학습',
    selfLearningDesc: '관심사에 기반한 맞춤형 학습 경로',
    otherModules: '기타 모듈',
    otherModulesDesc: '특정 목적을 위한 전문 학습',
    jobInterviewPrep: '면접 준비',
    jobInterviewPrepDesc: 'AI 시뮬레이션으로 면접 준비',
    presentationPrep: '프레젠테이션 준비',
    presentationPrepDesc: 'AI 피드백으로 스킬 향상',
    hobbyLearning: '취미 학습',
    hobbyLearningDesc: '체계적인 방법으로 새로운 기술 학습',
    learningPathways: '학습 경로',
    learningPathwaysDesc: '목표에 맞는 학습 경로를 선택하세요',
    recommended: '추천',
    startPersonalizedPlan: '맞춤 계획 시작',
    selectPathway: '경로 선택'
  },
  ar: {
    dashboard: 'لوحة التحكم',
    shop: 'المتجر',
    profile: 'الملف الشخصي',
    settings: 'الإعدادات',
    logout: 'تسجيل الخروج',
    login: 'تسجيل الدخول',
    signup: 'التسجيل',
    leaderboard: 'المتصدرين',
    friends: 'الأصدقاء',
    notifications: 'الإشعارات',
    premium: 'مميز',
    gameModes: 'أوضاع اللعب',
    singlePlayer: 'لاعب واحد',
    duos: 'زوجي',
    team: 'الفريق',
    ranked: 'مرتبة',
    exams: 'الامتحانات',
    progress: 'التقدم',
    startLearning: 'ابدأ التعلم',
    backTo: 'العودة إلى',
    lessons: 'الدروس',
    achievements: 'الإنجازات',
    streak: 'السلسلة',
    level: 'المستوى',
    xp: 'نقاط الخبرة',
    hours: 'ساعات',
    score: 'النتيجة',
    // Additional translations
    welcomeBack: 'مرحبا بعودتك!',
    learningProgress: 'إليك تقدمك في التعلم والتوصيات المدعومة بالذكاء الاصطناعي.',
    currentGrades: 'الدرجات الحالية',
    sync: 'مزامنة',
    aiRecommendations: 'توصيات الذكاء الاصطناعي',
    personalizedRecommendations: 'توصيات مخصصة بناءً على أدائك',
    quickActions: 'إجراءات سريعة',
    getStarted: 'ابدأ',
    viewProgress: 'عرض التقدم',
    days: 'أيام',
    day: 'يوم',
    streakCounter: '{{count}} أيام',
    streakCounter_one: '{{count}} يوم',
    streakCounter_other: '{{count}} أيام',
    hoursLearned: '{{count}} ساعات',
    hoursLearned_one: '{{count}} ساعة',
    hoursLearned_other: '{{count}} ساعات',
    levelUp: 'المستوى {{level}}',
    xpProgress: '{{current}}/{{total}} نقاط خبرة',
    achievementsUnlocked: '{{count}} إنجازات',
    achievementsUnlocked_one: '{{count}} إنجاز',
    achievementsUnlocked_other: '{{count}} إنجازات',
    lessonsCompleted: '{{count}} دروس',
    lessonsCompleted_one: '{{count}} درس',
    lessonsCompleted_other: '{{count}} دروس',
    // Progress page translations
    trackJourney: 'تتبع رحلة التعلم وإنجازاتك',
    completed: 'مكتمل',
    avgScore: 'متوسط الدرجة',
    studyTime: 'وقت الدراسة',
    acrossQuizzes: 'في جميع الاختبارات',
    totalLearningTime: 'إجمالي وقت التعلم',
    trends: 'الاتجاهات',
    recentActivity: 'النشاط الأخير',
    recentlyAccessed: 'دروسك التي تم الوصول إليها مؤخرًا',
    weeklyProgress: 'التقدم الأسبوعي',
    subjectPerformance: 'أداء المواد',
    outOf: 'من أصل',
    // Profile page translations
    addPeople: 'إضافة أشخاص',
    // Game modes translations
    challengeYourself: 'تحدى نفسك والآخرين في مختلف صيغ التعلم',
    currentRank: 'الترتيب الحالي',
    next: 'التالي',
    maxRank: 'الترتيب الأقصى!',
    season: 'الموسم',
    progressTo: 'التقدم نحو',
    max: 'الأقصى',
    yourStats: 'إحصائياتك',
    learningModules: 'وحدات التعلم',
    players: 'اللاعبون',
    difficulty: 'الصعوبة',
    rewards: 'المكافآت',
    start: 'ابدأ',
    specializedLearning: 'تعلم متخصص',
    explore: 'استكشف',
    // Wellness tab translations
    wellness: 'الصحة',
    wellnessCheckins: 'فحوصات الصحة',
    mood: 'المزاج',
    stress: 'الضغط',
    notes: 'الملاحظات',
    aiInsights: 'رؤى الذكاء الاصطناعي',
    noCheckinsYet: 'لا توجد فحوصات صحية بعد',
    lastCheckin: 'آخر فحص',
    daysAgo: 'منذ {{count}} أيام',
    daysAgo_one: 'منذ {{count}} يوم',
    daysAgo_other: 'منذ {{count}} أيام',
    // GameModes page translations
    programLearning: 'التعلم البرمجي',
    programLearningDesc: 'مسار تعليمي مخصص بناءً على أهدافك وقدراتك.',
    schoolLearning: 'التعلم المدرسي',
    schoolLearningDesc: 'التعلم وفقًا للمناهج الدراسية',
    selfLearning: 'التعلم الذاتي',
    selfLearningDesc: 'مسارات تعليمية مخصصة بناءً على اهتماماتك',
    otherModules: 'وحدات أخرى',
    otherModulesDesc: 'تعلم متخصص لحالات محددة',
    jobInterviewPrep: 'إعداد المقابلة',
    jobInterviewPrepDesc: 'استعد للمقابلات مع محاكاة الذكاء الاصطناعي',
    presentationPrep: 'إعداد العرض',
    presentationPrepDesc: 'حسّن مهاراتك مع ملاحظات الذكاء الاصطناعي',
    hobbyLearning: 'تعلم الهوايات',
    hobbyLearningDesc: 'تعلم مهارات جديدة بطريقة منظمة',
    learningPathways: 'مسارات التعلم',
    learningPathwaysDesc: 'اختر مسار التعلم المناسب لأهدافك',
    recommended: 'موصى به',
    startPersonalizedPlan: 'ابدأ خطة مخصصة',
    selectPathway: 'اختر المسار'
  },
  pt: {
    dashboard: 'Painel de Controle',
    shop: 'Loja',
    profile: 'Perfil',
    settings: 'Configurações',
    logout: 'Sair',
    login: 'Entrar',
    signup: 'Cadastre-se',
    leaderboard: 'Classificação',
    friends: 'Amigos',
    notifications: 'Notificações',
    premium: 'Premium',
    gameModes: 'Modos de Jogo',
    singlePlayer: 'Um Jogador',
    duos: 'Duplas',
    team: 'Equipe',
    ranked: 'Ranqueado',
    exams: 'Exames',
    progress: 'Progresso',
    startLearning: 'Começar a Aprender',
    backTo: 'Voltar para',
    lessons: 'Lições',
    achievements: 'Conquistas',
    streak: 'Sequência',
    level: 'Nível',
    xp: 'Pontos de Experiência',
    hours: 'Horas',
    score: 'Pontuação',
    // Additional translations
    welcomeBack: 'Bem-vindo de volta!',
    learningProgress: 'Aqui está o seu progresso de aprendizado e recomendações com IA.',
    currentGrades: 'Notas Atuais',
    sync: 'Sincronizar',
    aiRecommendations: 'Recomendações de IA',
    personalizedRecommendations: 'Recomendações personalizadas com base no seu desempenho',
    quickActions: 'Ações Rápidas',
    getStarted: 'Começar',
    viewProgress: 'Ver Progresso',
    days: 'dias',
    day: 'dia',
    streakCounter: '{{count}} dias',
    streakCounter_one: '{{count}} dia',
    streakCounter_other: '{{count}} dias',
    hoursLearned: '{{count}} horas',
    hoursLearned_one: '{{count}} hora',
    hoursLearned_other: '{{count}} horas',
    levelUp: 'Nível {{level}}',
    xpProgress: '{{current}}/{{total}} XP',
    achievementsUnlocked: '{{count}} conquistas',
    achievementsUnlocked_one: '{{count}} conquista',
    achievementsUnlocked_other: '{{count}} conquistas',
    lessonsCompleted: '{{count}} lições',
    lessonsCompleted_one: '{{count}} lição',
    lessonsCompleted_other: '{{count}} lições',
    // Progress page translations
    trackJourney: 'Acompanhe sua jornada de aprendizado e conquistas',
    completed: 'Concluído',
    avgScore: 'Pontuação Média',
    studyTime: 'Tempo de Estudo',
    acrossQuizzes: 'em todos os questionários',
    totalLearningTime: 'tempo total de aprendizado',
    trends: 'Tendências',
    recentActivity: 'Atividade Recente',
    recentlyAccessed: 'Suas lições acessadas mais recentemente',
    weeklyProgress: 'Progresso Semanal',
    subjectPerformance: 'Desempenho por Matéria',
    outOf: 'de',
    // Profile page translations
    addPeople: 'Adicionar Pessoas',
    // Game modes translations
    challengeYourself: 'Desafie-se e outros em vários formatos de aprendizado',
    currentRank: 'Classificação Atual',
    next: 'Próximo',
    maxRank: 'Classificação Máxima!',
    season: 'Temporada',
    progressTo: 'Progresso para',
    max: 'Máx',
    yourStats: 'Suas Estatísticas',
    learningModules: 'Módulos de Aprendizado',
    players: 'Jogadores',
    difficulty: 'Dificuldade',
    rewards: 'Recompensas',
    start: 'Começar',
    specializedLearning: 'Aprendizado Especializado',
    explore: 'Explorar',
    // Wellness tab translations
    wellness: 'Bem-estar',
    wellnessCheckins: 'Check-ins de Bem-estar',
    mood: 'Humor',
    stress: 'Estresse',
    notes: 'Notas',
    aiInsights: 'Insights de IA',
    noCheckinsYet: 'Ainda não há check-ins de bem-estar',
    lastCheckin: 'Último check-in',
    daysAgo: '{{count}} dias atrás',
    daysAgo_one: '{{count}} dia atrás',
    daysAgo_other: '{{count}} dias atrás',
    // GameModes page translations
    programLearning: 'Aprendizado Programado',
    programLearningDesc: 'Percurso de aprendizado personalizado baseado em seus objetivos.',
    schoolLearning: 'Aprendizado Escolar',
    schoolLearningDesc: 'Aprendizado alinhado ao currículo escolar',
    selfLearning: 'Autoaprendizado',
    selfLearningDesc: 'Percursos personalizados baseados em seus interesses',
    otherModules: 'Outros Módulos',
    otherModulesDesc: 'Aprendizado especializado para casos específicos',
    jobInterviewPrep: 'Preparação para Entrevista',
    jobInterviewPrepDesc: 'Prepare-se com simulações de IA',
    presentationPrep: 'Preparação de Apresentação',
    presentationPrepDesc: 'Melhore suas habilidades com feedback de IA',
    hobbyLearning: 'Aprendizado de Hobbies',
    hobbyLearningDesc: 'Aprenda novas habilidades de forma estruturada',
    learningPathways: 'Percursos de Aprendizado',
    learningPathwaysDesc: 'Escolha um percurso que corresponda aos seus objetivos',
    recommended: 'Recomendado',
    startPersonalizedPlan: 'Iniciar Plano Personalizado',
    selectPathway: 'Selecionar Percurso'
  },
  it: {
    dashboard: 'Cruscotto',
    shop: 'Negozio',
    profile: 'Profilo',
    settings: 'Impostazioni',
    logout: 'Esci',
    login: 'Accedi',
    signup: 'Registrati',
    leaderboard: 'Classifica',
    friends: 'Amici',
    notifications: 'Notifiche',
    premium: 'Premium',
    gameModes: 'Modalità di Gioco',
    singlePlayer: 'Giocatore Singolo',
    duos: 'Doppiette',
    team: 'Squadra',
    ranked: 'Classificato',
    exams: 'Esami',
    progress: 'Progresso',
    startLearning: 'Inizia ad Imparare',
    backTo: 'Torna a',
    lessons: 'Lezioni',
    achievements: 'Obiettivi',
    streak: 'Serie',
    level: 'Livello',
    xp: 'Punti Esperienza',
    hours: 'Ore',
    score: 'Punteggio',
    // Additional translations
    welcomeBack: 'Bentornato!',
    learningProgress: 'Ecco i tuoi progressi nell\'apprendimento e le raccomandazioni basate sull\'AI.',
    currentGrades: 'Voti Attuali',
    sync: 'Sincronizza',
    aiRecommendations: 'Raccomandazioni AI',
    personalizedRecommendations: 'Raccomandazioni personalizzate basate sulle tue prestazioni',
    quickActions: 'Azioni Veloci',
    getStarted: 'Inizia',
    viewProgress: 'Visualizza Progresso',
    days: 'giorni',
    day: 'giorno',
    streakCounter: '{{count}} giorni',
    streakCounter_one: '{{count}} giorno',
    streakCounter_other: '{{count}} giorni',
    hoursLearned: '{{count}} ore',
    hoursLearned_one: '{{count}} ora',
    hoursLearned_other: '{{count}} ore',
    levelUp: 'Livello {{level}}',
    xpProgress: '{{current}}/{{total}} PE',
    achievementsUnlocked: '{{count}} obiettivi',
    achievementsUnlocked_one: '{{count}} obiettivo',
    achievementsUnlocked_other: '{{count}} obiettivi',
    lessonsCompleted: '{{count}} lezioni',
    lessonsCompleted_one: '{{count}} lezione',
    lessonsCompleted_other: '{{count}} lezioni',
    // Progress page translations
    trackJourney: 'Traccia il tuo percorso di apprendimento e i tuoi obiettivi',
    completed: 'Completato',
    avgScore: 'Punteggio Medio',
    studyTime: 'Tempo di Studio',
    acrossQuizzes: 'in tutti i quiz',
    totalLearningTime: 'tempo totale di apprendimento',
    trends: 'Tendenze',
    recentActivity: 'Attività Recente',
    recentlyAccessed: 'Le tue lezioni accedute di recente',
    weeklyProgress: 'Progresso Settimanale',
    subjectPerformance: 'Prestazioni per Materia',
    outOf: 'su',
    // Profile page translations
    addPeople: 'Aggiungi Persone',
    // Game modes translations
    challengeYourself: 'Sfida te stesso e gli altri in vari formati di apprendimento',
    currentRank: 'Classifica Attuale',
    next: 'Successivo',
    maxRank: 'Classifica Massima!',
    season: 'Stagione',
    progressTo: 'Progresso verso',
    max: 'Massimo',
    yourStats: 'Le Tue Statistiche',
    learningModules: 'Moduli di Apprendimento',
    players: 'Giocatori',
    difficulty: 'Difficoltà',
    rewards: 'Ricompense',
    start: 'Inizia',
    specializedLearning: 'Apprendimento Specializzato',
    explore: 'Esplora',
    // Wellness tab translations
    wellness: 'Benessere',
    wellnessCheckins: 'Check-in Benessere',
    mood: 'Umore',
    stress: 'Stress',
    notes: 'Note',
    aiInsights: 'Approfondimenti AI',
    noCheckinsYet: 'Ancora nessun check-in benessere',
    lastCheckin: 'Ultimo check-in',
    daysAgo: '{{count}} giorni fa',
    daysAgo_one: '{{count}} giorno fa',
    daysAgo_other: '{{count}} giorni fa',
    // GameModes page translations
    programLearning: 'Apprendimento Programmato',
    programLearningDesc: 'Percorso di apprendimento personalizzato basato sui tuoi obiettivi.',
    schoolLearning: 'Apprendimento Scolastico',
    schoolLearningDesc: 'Apprendimento allineato al curriculum scolastico',
    selfLearning: 'Autoapprendimento',
    selfLearningDesc: 'Percorsi personalizzati basati sui tuoi interessi',
    otherModules: 'Altri Moduli',
    otherModulesDesc: 'Apprendimento specializzato per casi specifici',
    jobInterviewPrep: 'Preparazione Colloquio',
    jobInterviewPrepDesc: 'Preparati con simulazioni AI',
    presentationPrep: 'Preparazione Presentazione',
    presentationPrepDesc: 'Migliora le tue abilità con feedback AI',
    hobbyLearning: 'Apprendimento Hobby',
    hobbyLearningDesc: 'Impara nuove abilità in modo strutturato',
    learningPathways: 'Percorsi di Apprendimento',
    learningPathwaysDesc: 'Scegli un percorso che corrisponde ai tuoi obiettivi',
    recommended: 'Consigliato',
    startPersonalizedPlan: 'Inizia Piano Personalizzato',
    selectPathway: 'Seleziona Percorso'
  },
  es: {
    dashboard: 'Panel de Control',
    shop: 'Tienda',
    profile: 'Perfil',
    settings: 'Configuración',
    logout: 'Cerrar Sesión',
    login: 'Iniciar Sesión',
    signup: 'Registrarse',
    leaderboard: 'Clasificación',
    friends: 'Amigos',
    notifications: 'Notificaciones',
    premium: 'Premium',
    gameModes: 'Modos de Juego',
    singlePlayer: 'Un Jugador',
    duos: 'Parejas',
    team: 'Equipo',
    ranked: 'Clasificado',
    exams: 'Exámenes',
    progress: 'Progreso',
    startLearning: 'Comenzar a Aprender',
    backTo: 'Volver a',
    lessons: 'Lecciones',
    achievements: 'Logros',
    streak: 'Racha',
    level: 'Nivel',
    xp: 'Puntos de Experiencia',
    hours: 'Horas',
    score: 'Puntuación',
    welcomeBack: '¡Bienvenido de nuevo!',
    learningProgress: 'Aquí está tu progreso de aprendizaje y recomendaciones con IA.',
    currentGrades: 'Calificaciones Actuales',
    sync: 'Sincronizar',
    aiRecommendations: 'Recomendaciones de IA',
    personalizedRecommendations: 'Recomendaciones personalizadas basadas en tu rendimiento',
    quickActions: 'Acciones Rápidas',
    getStarted: 'Comenzar',
    viewProgress: 'Ver Progreso',
    days: 'días',
    day: 'día',
    programLearning: 'Aprendizaje Programado',
    programLearningDesc: 'Ruta de aprendizaje personalizada basada en tus objetivos.',
    schoolLearning: 'Aprendizaje Escolar',
    schoolLearningDesc: 'Aprendizaje alineado con el currículo escolar',
    selfLearning: 'Autoaprendizaje',
    selfLearningDesc: 'Rutas personalizadas basadas en tus intereses',
    otherModules: 'Otros Módulos',
    otherModulesDesc: 'Aprendizaje especializado para casos específicos',
    jobInterviewPrep: 'Preparación de Entrevista',
    jobInterviewPrepDesc: 'Prepárate con simulaciones de IA',
    presentationPrep: 'Preparación de Presentación',
    presentationPrepDesc: 'Mejora tus habilidades con retroalimentación de IA',
    hobbyLearning: 'Aprendizaje de Hobbies',
    hobbyLearningDesc: 'Aprende nuevas habilidades de forma estructurada',
    learningPathways: 'Rutas de Aprendizaje',
    learningPathwaysDesc: 'Elige una ruta que se adapte a tus objetivos',
    recommended: 'Recomendado',
    startPersonalizedPlan: 'Iniciar Plan Personalizado',
    selectPathway: 'Seleccionar Ruta'
  },
  fr: {
    dashboard: 'Tableau de Bord',
    shop: 'Boutique',
    profile: 'Profil',
    settings: 'Paramètres',
    logout: 'Déconnexion',
    login: 'Connexion',
    signup: 'S\'inscrire',
    leaderboard: 'Classement',
    friends: 'Amis',
    notifications: 'Notifications',
    premium: 'Premium',
    gameModes: 'Modes de Jeu',
    singlePlayer: 'Joueur Solo',
    duos: 'Duos',
    team: 'Équipe',
    ranked: 'Classé',
    exams: 'Examens',
    progress: 'Progrès',
    startLearning: 'Commencer à Apprendre',
    backTo: 'Retour à',
    lessons: 'Leçons',
    achievements: 'Réalisations',
    streak: 'Série',
    level: 'Niveau',
    xp: 'Points d\'Expérience',
    hours: 'Heures',
    score: 'Score',
    welcomeBack: 'Bon retour!',
    learningProgress: 'Voici votre progression et recommandations IA.',
    currentGrades: 'Notes Actuelles',
    sync: 'Synchroniser',
    aiRecommendations: 'Recommandations IA',
    personalizedRecommendations: 'Recommandations personnalisées selon vos performances',
    quickActions: 'Actions Rapides',
    getStarted: 'Commencer',
    viewProgress: 'Voir le Progrès',
    days: 'jours',
    day: 'jour',
    programLearning: 'Apprentissage Programmé',
    programLearningDesc: 'Parcours personnalisé basé sur vos objectifs.',
    schoolLearning: 'Apprentissage Scolaire',
    schoolLearningDesc: 'Apprentissage aligné sur le programme scolaire',
    selfLearning: 'Auto-apprentissage',
    selfLearningDesc: 'Parcours personnalisés selon vos intérêts',
    otherModules: 'Autres Modules',
    otherModulesDesc: 'Apprentissage spécialisé pour des cas spécifiques',
    jobInterviewPrep: 'Préparation Entretien',
    jobInterviewPrepDesc: 'Préparez-vous avec des simulations IA',
    presentationPrep: 'Préparation Présentation',
    presentationPrepDesc: 'Améliorez vos compétences avec le feedback IA',
    hobbyLearning: 'Apprentissage Loisirs',
    hobbyLearningDesc: 'Apprenez de nouvelles compétences de manière structurée',
    learningPathways: 'Parcours d\'Apprentissage',
    learningPathwaysDesc: 'Choisissez un parcours adapté à vos objectifs',
    recommended: 'Recommandé',
    startPersonalizedPlan: 'Démarrer Plan Personnalisé',
    selectPathway: 'Sélectionner Parcours'
  },
  de: {
    dashboard: 'Übersicht',
    shop: 'Shop',
    profile: 'Profil',
    settings: 'Einstellungen',
    logout: 'Abmelden',
    login: 'Anmelden',
    signup: 'Registrieren',
    leaderboard: 'Rangliste',
    friends: 'Freunde',
    notifications: 'Benachrichtigungen',
    premium: 'Premium',
    gameModes: 'Spielmodi',
    singlePlayer: 'Einzelspieler',
    duos: 'Duos',
    team: 'Team',
    ranked: 'Rangliste',
    exams: 'Prüfungen',
    progress: 'Fortschritt',
    startLearning: 'Lernen Starten',
    backTo: 'Zurück zu',
    lessons: 'Lektionen',
    achievements: 'Erfolge',
    streak: 'Serie',
    level: 'Stufe',
    xp: 'Erfahrungspunkte',
    hours: 'Stunden',
    score: 'Punktzahl',
    welcomeBack: 'Willkommen zurück!',
    learningProgress: 'Hier ist Ihr Lernfortschritt und KI-Empfehlungen.',
    currentGrades: 'Aktuelle Noten',
    sync: 'Synchronisieren',
    aiRecommendations: 'KI-Empfehlungen',
    personalizedRecommendations: 'Personalisierte Empfehlungen basierend auf Ihrer Leistung',
    quickActions: 'Schnelle Aktionen',
    getStarted: 'Starten',
    viewProgress: 'Fortschritt Anzeigen',
    days: 'Tage',
    day: 'Tag',
    programLearning: 'Programmiertes Lernen',
    programLearningDesc: 'Personalisierter Lernpfad basierend auf Ihren Zielen.',
    schoolLearning: 'Schulisches Lernen',
    schoolLearningDesc: 'Lernen nach dem Schullehrplan',
    selfLearning: 'Selbststudium',
    selfLearningDesc: 'Personalisierte Pfade basierend auf Ihren Interessen',
    otherModules: 'Andere Module',
    otherModulesDesc: 'Spezialisiertes Lernen für spezifische Fälle',
    jobInterviewPrep: 'Vorstellungsgespräch-Vorbereitung',
    jobInterviewPrepDesc: 'Bereiten Sie sich mit KI-Simulationen vor',
    presentationPrep: 'Präsentationsvorbereitung',
    presentationPrepDesc: 'Verbessern Sie Ihre Fähigkeiten mit KI-Feedback',
    hobbyLearning: 'Hobby-Lernen',
    hobbyLearningDesc: 'Lernen Sie neue Fähigkeiten strukturiert',
    learningPathways: 'Lernpfade',
    learningPathwaysDesc: 'Wählen Sie einen Pfad, der zu Ihren Zielen passt',
    recommended: 'Empfohlen',
    startPersonalizedPlan: 'Personalisierten Plan Starten',
    selectPathway: 'Pfad Auswählen'
  },
  uk: {
    dashboard: 'Панель управління',
    shop: 'Магазин',
    profile: 'Профіль',
    settings: 'Налаштування',
    logout: 'Вийти',
    login: 'Увійти',
    signup: 'Реєстрація',
    leaderboard: 'Таблиця лідерів',
    friends: 'Друзі',
    notifications: 'Сповіщення',
    premium: 'Преміум',
    gameModes: 'Режими гри',
    singlePlayer: 'Одиночна гра',
    duos: 'Дуети',
    team: 'Команда',
    ranked: 'Рейтингова',
    exams: 'Екзамени',
    progress: 'Прогрес',
    startLearning: 'Почати навчання',
    backTo: 'Повернутися до',
    lessons: 'Уроки',
    achievements: 'Досягнення',
    streak: 'Серія',
    level: 'Рівень',
    xp: 'Очки досвіду',
    hours: 'Години',
    score: 'Рахунок',
    welcomeBack: 'З поверненням!',
    learningProgress: 'Ваш прогрес та рекомендації ШІ.',
    currentGrades: 'Поточні оцінки',
    sync: 'Синхронізувати',
    aiRecommendations: 'Рекомендації ШІ',
    personalizedRecommendations: 'Персоналізовані рекомендації на основі ваших результатів',
    quickActions: 'Швидкі дії',
    getStarted: 'Почати',
    viewProgress: 'Переглянути прогрес',
    days: 'днів',
    day: 'день',
    programLearning: 'Програмне навчання',
    programLearningDesc: 'Персоналізований шлях навчання на основі ваших цілей.',
    schoolLearning: 'Шкільне навчання',
    schoolLearningDesc: 'Навчання за шкільною програмою',
    selfLearning: 'Самонавчання',
    selfLearningDesc: 'Персоналізовані шляхи на основі ваших інтересів',
    otherModules: 'Інші модулі',
    otherModulesDesc: 'Спеціалізоване навчання для конкретних випадків',
    jobInterviewPrep: 'Підготовка до співбесіди',
    jobInterviewPrepDesc: 'Готуйтесь з симуляціями ШІ',
    presentationPrep: 'Підготовка презентації',
    presentationPrepDesc: 'Покращуйте навички за допомогою зворотного зв’язку ШІ',
    hobbyLearning: 'Хобі-навчання',
    hobbyLearningDesc: 'Вивчайте нові навички структуровано',
    learningPathways: 'Навчальні шляхи',
    learningPathwaysDesc: 'Оберіть шлях, що відповідає вашим цілям',
    recommended: 'Рекомендовано',
    startPersonalizedPlan: 'Почати персоналізований план',
    selectPathway: 'Обрати шлях'
  }
};

i18n.use(initReactI18next).init({
  resources: {
    en: { translation: translations.en },
    lt: { translation: translations.lt },
    zh: { translation: translations.zh },
    ja: { translation: translations.ja },
    ko: { translation: translations.ko },
    ar: { translation: translations.ar },
    pt: { translation: translations.pt },
    it: { translation: translations.it },
    es: { translation: translations.es },
    fr: { translation: translations.fr },
    de: { translation: translations.de },
    uk: { translation: translations.uk }
  },
  lng: localStorage.getItem('language') || 'en',
  fallbackLng: 'en',
  interpolation: { 
    escapeValue: false,
    format: function(value, format, lng) {
      if (format === 'uppercase') return value.toUpperCase();
      if (format === 'lowercase') return value.toLowerCase();
      return value;
    }
  }
});

interface LanguageContextType {
  language: string;
  changeLanguage: (lng: string) => void;
  t: (key: string, options?: Record<string, any>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState(i18n.language);

  useEffect(() => {
    // Load language from localStorage on initial load
    const savedLanguage = localStorage.getItem('language');
    if (savedLanguage && translations[savedLanguage as keyof typeof translations]) {
      i18n.changeLanguage(savedLanguage);
      setLanguage(savedLanguage);
    }
  }, []);

  const changeLanguage = (lng: string) => {
    i18n.changeLanguage(lng);
    setLanguage(lng);
    localStorage.setItem('language', lng);
  };

  const t = (key: string, options?: Record<string, any>): string => String(i18n.t(key, options));

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};